# Generated by Django 5.1.1 on 2024-09-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_participant_meetupmodel_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupmodel',
            name='date',
            field=models.DateField(default='2024-03-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetupmodel',
            name='organazier_email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
